Upgrade the module to compatible with ss4
SilbinaryWolf/silverstripe-steamedclams pull request #13
Opened 2019-03-26 02:45 UTC by ishannz

2019-03-26 23:48 UTC, nglasl commented
Thanks for the PR here @ishannz!

2019-04-11 00:09 UTC, JoshuaCarter requested changes
Hey @ishannz ! Thanks for the PR and your patience :)

I've requested some minor changes. Please take a look and feel free to contest me on any points you think I might be wrong about, etc. Can I also ask to what degree you've tested this PR? I want to gauge the degree of testing we may need to do on our end.

Great work here so far!

2019-04-11 00:09 UTC, JoshuaCarter commented on README.md
> +1) Install ClamAV in ubuntu.
afaik this should read 'debian' rather than 'ubuntu', but I could be wrong.

2019-04-11 00:09 UTC, JoshuaCarter commented on README.md
> +2) Start clamav-daemon - Please wait 2 minutes between two command.
This renders on the line above, i.e. `[...] necessary. 2) Start  clamav-daemon [...]`, probably needs a linebreak.

2019-04-11 00:09 UTC, JoshuaCarter commented on README.md
> +sudo service clamav-daemon start
Maybe put the above comment about waiting 2 minutes between these commands in here so that people can't miss it, i.e.
```
sudo service clamav-freshclam restart
# wait ~2 minutes
sudo service clamav-daemon start
```

2019-04-11 00:09 UTC, JoshuaCarter commented on README.md
>  NOTE: I am by no means a *nix/server expert, but this is what I did to get it going.
Can remove this note I think :)

2019-04-11 00:09 UTC, JoshuaCarter commented on README.md
>  sudo chown -R defaultsite:defaultsite /var/run/clamav
IMO replace `defaultsite:defaultsite` with `user:group`.

2019-04-11 00:09 UTC, JoshuaCarter commented on composer.json
> -            "dev-master": "2.0.x-dev"
The branch alias should be changed to `3.0.x-dev` rather than removed.

2019-04-11 00:09 UTC, JoshuaCarter commented on src/Admin/ClamAVAdmin.php
>      {
Line 68 has `singleton('AssetAdmin');` where the string should be `AssetAdmin::class` (and matching use statement).

2019-04-11 00:09 UTC, JoshuaCarter commented on src/ClamAV.php
> +            $result = Injector::inst()->create('ClamdPipe');
This could be `ClamdPipe::class`.

2019-04-11 00:09 UTC, JoshuaCarter commented on src/Extension/ClamAVExtension.php
> +        $fileMetaData = $this->owner->File->getMetadata();
Should probably check that file exists before this.

2019-04-11 00:09 UTC, JoshuaCarter commented on src/Jobs/ClamAVScanJob.php
> +            $job = Injector::inst()->get('QueuedJobService');
This should be `QueuedJobService::class` (and matching `use` statement).

2019-04-11 00:09 UTC, JoshuaCarter commented on src/Tasks/ClamAVInstallTask.php
>  class ClamAVInstallTask extends ClamAVBaseTask
Need a use statement for ClamAVBaseTask.

2019-04-11 00:09 UTC, JoshuaCarter commented on src/Tasks/ClamAVScanTask.php
>  class ClamAVScanTask extends ClamAVBaseTask
Need a use statement for ClamAVBaseTask.

2019-04-11 00:09 UTC, JoshuaCarter commented on tests/ClamAVExtensionTest.php
Need a use statement for ClamAVEmulator and ClamAV.

2019-04-11 05:59 UTC, ishannz commented on README.md
> +1) Install ClamAV in ubuntu.
We can change this to `Unix/Linux`

2019-04-11 06:00 UTC, ishannz commented on src/Tasks/ClamAVInstallTask.php
>  class ClamAVInstallTask extends ClamAVBaseTask
No need, because both are in the same namespace.

2019-04-11 06:00 UTC, ishannz commented on src/Tasks/ClamAVScanTask.php
>  class ClamAVScanTask extends ClamAVBaseTask
Same here,

2019-04-11 06:05 UTC, ishannz commented on tests/ClamAVExtensionTest.php
No need. all are in the same namespace `Symbiote\SteamedClams`.

2019-04-12 02:37 UTC, ishannz commented
@JoshuaCarter Thanks for reviewing my code. Apply code changes which you recommended, Please recheck when you free.

2019-10-01 05:48 UTC, nglasl commented
@ishannz apologies for the delay here, but this has some conflicts that need to be resolved before it can be merged. @JoshuaCarter have you had a chance to review the changes that were made?

2019-10-02 06:39 UTC, JoshuaCarter requested changes
Hey @ishannz, sorry for letting this fall by the wayside. Once again thanks for the great work, this just needs a few tiny adjustments and conflicts resolved. Once done please ping me and I'll merge it :)

2019-10-02 06:39 UTC, JoshuaCarter commented on src/Admin/ClamAVAdmin.php
>      {
This still needs a `use` statement for `AssetAdmin`.

2019-10-02 06:39 UTC, JoshuaCarter commented on README.md
> +sudo service clamav-daemon start
This isn't a big deal but would be nice to add if/when other fixes go in.

2019-10-02 06:39 UTC, JoshuaCarter commented on src/ClamAV.php
> +            $result = Injector::inst()->create('ClamdPipe');
This still needs doing.

2019-11-22 00:54 UTC, ishannz commented
@JoshuaCarter all the fixes have been applied. apologies for the late response.

2019-11-22 23:43 UTC, JoshuaCarter approved these changes

2019-11-22 23:51 UTC, merged

2019-11-22 23:59 UTC, JoshuaCarter commented
@ishannz @nglasl 

Excellent work ishannz, many thanks for that!

I branched master off into a `2` branch in case the SS3 version needs future work, and made a 3.0.0 release for these changes.